excluded: 
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swif
  - Source/Supporting/Base/BaseViewController.swift
disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - nesting
  - identifier_name
warning_threshold: 5
